### ISSUE TITLE
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by pengssy** [uc-vision/smart-tree#1]
Hi author!

I met this problem on my windows machine when I uesed bash create-env.sh to intall this packege.
Do you know how to solve it?
Thanks!
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
![37160f70dcbfb1d697a251fb3b34483](https://github.com/uc-vision/smart-tree/assets/72547419/51769993-cd9c-4505-b61f-96826644827a)

**Comment by harrydobbs** [comment]
Hi @pengssy ,

Thanks for the message. I see you have closed the issue - could you please advise or do a pull request on the required changes to get it operating on windows? I have only tested the install on Linux, but once I am back from overseas (~ 2 weeks) I will look into this. Was the bash script being called within the directory?

Cheers,
Harry

**Comment by pengssy** [comment]
Hi Harry,


I closed it because I found this package has already in my package list. But I met a another problem when I was trying to run it on the windows machine: need to install 'fcntl', but seems like fcntl donot surport windows.


Cheers,
Xi







Pengg
***@***.***







                       
Original Email
                       
                     

Sender:"harrydobbs"< ***@***.*** &gt;;

Sent Time:2023/6/29 12:10

To:"uc-vision/smart-tree"< ***@***.*** &gt;;

Cc recipient:"Pengssy"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [uc-vision/smart-tree] ERROR: Directory '.' is not installable.Neither 'setup.py' nor 'pyproject.toml' found. (Issue #1)




 
Hi @pengssy ,
 
Thanks for the message. I see you have closed the issue - could you please advise or do a pull request on the required changes to get it operating on windows? I have only tested the install on Linux, but once I am back from overseas (~ 2 weeks) I will look into this.
 
Cheers,
 Harry

**Comment by harrydobbs** [comment]
Okay thanks for letting me know. Will see what I can do when I get back. 😎

**Comment by pengssy** [comment]
Thanks!


Xi



Pengg
***@***.***







                       
Original Email
                       
                     

Sender:"harrydobbs"< ***@***.*** &gt;;

Sent Time:2023/6/29 16:35

To:"uc-vision/smart-tree"< ***@***.*** &gt;;

Cc recipient:"Pengssy"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [uc-vision/smart-tree] ERROR: Directory '.' is not installable.Neither 'setup.py' nor 'pyproject.toml' found. (Issue #1)




 
Okay thanks for letting me know. Will see what I can do when I get back. 😎
