### ISSUE TITLE
Inference on the non -default GPU，such as "cuda:5"

### ISSUE THREAD

**Issue by liyaoyuhub** [uc-vision/smart-tree#10]
Thank you very much for your amazing work, but I encountered some problems when doing inference with the existing model and parameters: 

1. When I specify the number of the GPU, I always find that the program will run on the default GPU (cuda:0) Simultaneously load an identical model. 

2. I often encounter program jams when inferencing. I am not sure whether it is related to the first point.

I would like to understand how long normal inferencing takes and if there is a way to solve my problem. Thank you again for your outstanding contribution to this work.

**Comment by harrydobbs** [comment]
Hi there,

1) Inference on non-default GPU is currently not supported. I will add this feature in the future.
2) Regarding the processing speed, the duration can vary depending on the complexity and characteristics of the data. If the network struggles to accurately estimate the medial axis, it might result in longer processing times. This is particularly true for data that significantly deviates from the training set's domain. Generally, the process should complete within a few minutes. To help diagnose your specific case, could you send me the data you're using (hdo27@uclive.ac.nz) ? Alternatively what is the output in the terminal when the program jams?

Cheers,
Harry

**Comment by liyaoyuhub** [comment]
I'm glad to receive your reply, I think my doubts have been resolved. In addition, the reason why the inference process was blocked may be because I tried to modify the GPU index involved in the project, which may have caused the network model to not be loaded or not located on the GPU I specified. I'll try to resolve this issue, thank you very much for your reply!
