### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_customAllocator'

### ISSUE THREAD

**Issue by LANXIAODDD** [uc-vision/smart-tree#12]
**Hello author,** 
 I have some questions for you.
After I  installed my environment following bash commands, I am trying to infer my own data based on the existing model.But I am facing problem: 
run-smart-tree +path= xxx
![image](https://github.com/uc-vision/smart-tree/assets/79525202/90d182d1-a0ba-4178-a3fb-72b0c2ff7ed2)

Can you please tell me how to solve this problem?

**Comment by harrydobbs** [comment]
Hello, 

Ah not too sure, I haven't come across that before.

What happens when you run the following:

`python -c "import torch; print(torch.cuda.is_available())`
`nvidia-smi`



Cheers,
Harry

**Comment by LANXIAODDD** [comment]
Yes, there is a problem.
![image](https://github.com/uc-vision/smart-tree/assets/79525202/c1637dfc-b12a-4e9a-b0d9-bf910ed8b4e3)

My GPU is
![image](https://github.com/uc-vision/smart-tree/assets/79525202/bd8e65b6-0a5a-457d-8cf6-74690b02705d)
I'm new to this, so I'd like to know how I can make changes to the smart-tree environment

**Comment by harrydobbs** [comment]
Ah okay, you need to have pytorch installed with cuda - this command should work:

`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by harrydobbs** [comment]
You need to have pytorch install with cuda - https://pytorch.org/get-started/locally/

**Comment by LANXIAODDD** [comment]
Thanks！
I successfully ran run-smart-tree
But if I infer  my own data, the txt file containing only xyz information:
![image](https://github.com/uc-vision/smart-tree/assets/79525202/391afe10-7428-4a12-a689-13152e04a69e)

An error is reported (I have converted the txt to npz format)
What should I do with my data?

**Comment by harrydobbs** [comment]
What is the error?

The cloud loader should support .ply .pcd and .txt files.

**Comment by LANXIAODDD** [comment]
.txt:
![image](https://github.com/uc-vision/smart-tree/assets/79525202/c2268a50-9631-453c-8f5e-e23d92a04d1b)

.ply:
![image](https://github.com/uc-vision/smart-tree/assets/79525202/06337fce-fa64-47cc-aaf7-b3f9c6caf5e5)

**Comment by harrydobbs** [comment]
Just fixed it, there was a minor bug if the cloud didn't have RGB.

**Comment by away-back** [comment]
Excuse me，have you solved the no-rgb point cloud problem? 


> Thanks！   I successfully ran run-smart-tree But if I infer my own data, the txt file containing only xyz information: ![image](https://github.com/uc-vision/smart-tree/assets/79525202/391afe10-7428-4a12-a689-13152e04a69e)
> 
> An error is reported (I have converted the txt to npz format) What should I do with my data?
