### ISSUE TITLE
hydra.errors.MissingConfigException: Primary config module 'smart_tree..conf' not found when running 'run-smart-tree'

### ISSUE THREAD

**Issue by EugeneKok97** [uc-vision/smart-tree#3]
Hi there, I've encountered an error when running `run-smart-tree +path=/home/lmga-titanx/smart-tree/apple/apple_1/xyz.npy`, where `/home/lmga-titanx/smart-tree/apple/apple_1/xyz.npy` is the cloud path of one of the apple trees downloaded from the given data. Here is the traceback of the error:

![Screenshot from 2023-08-15 13-23-52](https://github.com/uc-vision/smart-tree/assets/72436847/a839cb92-93e9-442b-a181-fe36e0659c7a)

**Comment by EugeneKok97** [comment]
I was able to resolve the issue by changing the `config_path` from `'.conf'` to `'conf'` in the cli.py file, and also changing the cloud_path to .../apple_1.npz.

**Comment by harrydobbs** [comment]
Thanks for letting me know.
