### ISSUE TITLE
How do you get Mesh output and Skeleton output from inference as shown in README.md?

### ISSUE THREAD

**Issue by EugeneKok97** [uc-vision/smart-tree#4]
Among the geometries given in the visualization window, I couldn't find one that has the skeleton and mesh output. Can you please guide me on how to obtain the skeleton and mesh output?

![Screenshot from 2023-08-15 14-24-36](https://github.com/uc-vision/smart-tree/assets/72436847/c648fe07-77fc-4a3f-88e4-93df3bfc6b5d)

**Comment by harrydobbs** [comment]
The visualizers display the neural network output and then the skeleton. 
![network](https://github.com/uc-vision/smart-tree/assets/27661260/8c8598f5-05a1-48ec-b685-f20ca79ae876)
![skeleton](https://github.com/uc-vision/smart-tree/assets/27661260/19430fb9-bec7-46b5-a12e-b95dc86dc23c)

These can be enabled/disabled in the pipeline config file: https://github.com/uc-vision/smart-tree/blob/main/smart_tree/conf/pipeline.yaml

Additional settings regarding saving the outputs are set here too.
