### ISSUE TITLE
Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by EugeneKok97** [uc-vision/smart-tree#5]
During the skeletonization process, The subgraph process stops at 11% with the following error:

![Screenshot from 2023-08-15 15-29-24](https://github.com/uc-vision/smart-tree/assets/72436847/5f9315a7-5a43-4218-8fa9-3b8b3f91df82)

**Comment by harrydobbs** [comment]
Probably running out of GPU memory. In the config file try reducing:

`max_number_components `

**Comment by harrydobbs** [comment]
Fixed - should be fine now. Thanks.
