### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by EugeneKok97** [uc-vision/smart-tree#9]
Hi, there is a new error with the latest version when running `run-smart-tree`.
 
ERROR:
File "/home/lmga-titanx/smart-tree/smart_tree/cli.py", line 24, in main
    pipeline.process_cloud(Path(cfg.path))
  File "/home/lmga-titanx/smart-tree/smart_tree/pipeline.py", line 68, in process_cloud
    cloud = self.preprocessing(cloud)
  File "/home/lmga-titanx/smart-tree/smart_tree/dataset/augmentations.py", line 117, in __call__
    cloud = augmentation(cloud)
  File "/home/lmga-titanx/smart-tree/smart_tree/dataset/augmentations.py", line 42, in __call__
    centre, (x, y, z) = cloud.bbox
  File "/home/lmga-titanx/anaconda3/envs/smart-tree/lib/python3.8/site-packages/typeguard/__init__.py", line 910, in wrapper
    memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
  File "/home/lmga-titanx/anaconda3/envs/smart-tree/lib/python3.8/site-packages/typeguard/__init__.py", line 129, in __init__
    hints = get_type_hints(func, localns=frame_locals)
  File "/home/lmga-titanx/anaconda3/envs/smart-tree/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/home/lmga-titanx/anaconda3/envs/smart-tree/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/home/lmga-titanx/anaconda3/envs/smart-tree/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable

**Comment by harrydobbs** [comment]
I don't get that error.  Are you sure you have the latest version? 
What does `git show` return?
Please share your config file.
`run-smart-tree` is not a standalone command - it requires the path of a point cloud you want to skeletonize - what is the full command you are running?

**Comment by harrydobbs** [comment]
I don't get that error. Are you sure you have the latest version?
Please share your config file.
run-smart-tree is not a standalone command - it requires the path of a point cloud you want to skeletonize - What is the full command you are running?

**Comment by EugeneKok97** [comment]
`git show`:

![Screenshot from 2023-08-30 11-05-36](https://github.com/uc-vision/smart-tree/assets/72436847/2c3a8537-fac4-4e20-b578-6c534a936cb1)

config file:
```
pipeline:
  _target_: smart_tree.pipeline.Pipeline
  
  preprocessing:
    _target_: smart_tree.dataset.augmentations.AugmentationPipeline
    augmentations: 
      - _target_:  smart_tree.dataset.augmentations.CentreCloud

  model_inference: 
    _target_: smart_tree.model.model_inference.ModelInference
    model_path: smart_tree/model/weights/noble-elevator-58_model.pt
    weights_path: smart_tree/model/weights/noble-elevator-58_model_weights.pt
    voxel_size: 0.01
    block_size: 4
    buffer_size: 0.4
    num_workers : 8
    batch_size : 4

  skeletonizer:
    _target_: smart_tree.skeleton.skeletonize.Skeletonizer
    K: 16
    min_connection_length: 0.02 
    minimum_graph_vertices: 32

  view_model_output : False
  view_skeletons : False
  save_path: /
  save_outputs : False
  
  branch_classes: [0]
  cmap:
    - [0.450, 0.325, 0.164] # Trunk
    - [0.541, 0.670, 0.164] # Foliage

  repair_skeletons : True
  smooth_skeletons : True
  smooth_kernel_size: 11 # Needs to be odd
  prune_skeletons : True 
  min_skeleton_radius : 0.01 
  min_skeleton_length : 0.02
```

full command :  `run-smart-tree +path=/home/lmga-titanx/winter_tree_tof_dataset/merged.npz`

merged.npz contains both xyz.npy and rgb.npy files with the size of (40680,3).

**Comment by harrydobbs** [comment]
Hi, 

I just installed it freshly on a different PC, everything works fine for me.
Maybe you need to run `pip install .` again.
If that doesn't work - can you send me your data or test with some of the supplied data, please?

Let me know how you get on.
Cheers

**Comment by EugeneKok97** [comment]
`pip install .` solved the issue. Thank you!

**Comment by harrydobbs** [comment]
No worries! I hope it worked well on your data.
